name: muse_http_controller
author: Ryan Hair <ryandhair@gmail.com>
version: 0.1.2
homepage: https://github.com/ryanhair/muse
description: Http controller implementation for Muse framework
documentation: https://github.com/ryanhair/muse
dependencies:
  muse_core:
    path: ../muse_core
