name: car_lot
description: A sample command-line application
dependencies:
  angular: any
  browser: any
  js: any
  muse_core:
    path: ../../muse_core
  muse_http_controller:
    path: ../../../Muse/muse_http_controller
  muse_mongo_repo:
    path: ../../../Muse/muse_mongo_repo
  uuid: any
