name: muse_framework
author: Ryan Hair
description: A sample application
dependencies:
  muse:
    path: ../Muse
  muse_controller:
    path: ../MuseController
  muse_model:
    path: ../MuseModel
  muse_repo:
    path: ../MuseRepo
  muse_service:
    path: ../MuseService
