name: muse_mongo_repo
version: 0.1.1
author: Ryan Hair <ryandhair@gmail.com>
description: Mongo repository implementation for Muse framework
homepage: https://github.com/ryanhair/muse
documentation: https://github.com/ryanhair/muse
dependencies:
  mongo_dart: 0.1.42
  muse_core:
    path: ../muse_core
  uuid: 0.3.2
