name:  muse_mongo_repo
description: Mongo repository implementation for Muse framework 

dependencies:
  muse:
    path: ../Muse
  muse_repo:
    path: ../MuseRepo
  muse_model:
    path: ../MuseModel
  mongo_dart: any
  uuid: any